# -*- coding: utf-8 -*-
"""betternews_tracking_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PiuvMqaPzjw2qAj4-Ghsvv88pTA-66kD
"""

import mlflow
from mlflow import log_metric, log_param
from betternews_testmodel import train_models  # Ensure this import is correct

# Initialize MLflow
mlflow.set_experiment("Better-News Category Classification")

def track_experiment():
    with mlflow.start_run():
        # Train models and retrieve model and accuracy
        model, accuracy = train_models()

        # Log parameters
        log_param("model_type", "VotingClassifier")
        log_param("n_estimators", 50)  # Example parameter

        # Log metrics
        print("Logging accuracy:", accuracy)  # Verify accuracy is being logged
        log_metric("accuracy", accuracy)  # Log accuracy as a metric

        # Save and log model
        mlflow.sklearn.log_model(model, "model")

# Execute the tracking function
if __name__ == "__main__":
    track_experiment()


